// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-lRGWpyiJ3D9RzxuEdRqJypjTfuYknlo',
    appId: '1:769354509306:web:ae338108682f4b45ee1243',
    messagingSenderId: '769354509306',
    projectId: 'cinescoopapp-50141',
    authDomain: 'cinescoopapp-50141.firebaseapp.com',
    storageBucket: 'cinescoopapp-50141.appspot.com',
    measurementId: 'G-JP9V030WRS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTTp3RDCAoA2QE6QbAqo42vYGTfR2GFs4',
    appId: '1:769354509306:android:6d472227a881ee68ee1243',
    messagingSenderId: '769354509306',
    projectId: 'cinescoopapp-50141',
    storageBucket: 'cinescoopapp-50141.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjTsouns_5kSuO39sWgWYJUbVKYNCtDmA',
    appId: '1:769354509306:ios:1405a0803e9edfe5ee1243',
    messagingSenderId: '769354509306',
    projectId: 'cinescoopapp-50141',
    storageBucket: 'cinescoopapp-50141.appspot.com',
    iosBundleId: 'com.example.cinescoopUasmobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjTsouns_5kSuO39sWgWYJUbVKYNCtDmA',
    appId: '1:769354509306:ios:6d05feb415b21f0eee1243',
    messagingSenderId: '769354509306',
    projectId: 'cinescoopapp-50141',
    storageBucket: 'cinescoopapp-50141.appspot.com',
    iosBundleId: 'com.example.cinescoopUasmobile.RunnerTests',
  );
}
